//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appUserAccess
    {
        public int appuseraccessid { get; set; }
        public Nullable<int> appuserid { get; set; }
        public Nullable<int> appmoduleid { get; set; }
        public Nullable<bool> appinsert { get; set; }
        public Nullable<bool> appedit { get; set; }
        public Nullable<bool> appdelete { get; set; }
        public Nullable<bool> appview { get; set; }
    }
}
