//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_OffsetApplication
    {
        public int OffsetID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public string DTRIn { get; set; }
        public string DTROut { get; set; }
        public Nullable<decimal> EarnedHours { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> HRApprovedBy { get; set; }
        public Nullable<System.DateTime> HRApprovedDate { get; set; }
    }
}
