//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpWorkHistory
    {
        public int workID { get; set; }
        public Nullable<int> empID { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public Nullable<int> SalaryGradeID { get; set; }
        public Nullable<int> SGIncrementID { get; set; }
        public Nullable<int> AppointmentStatusID { get; set; }
        public Nullable<bool> IsGovService { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
    }
}
