//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IrrigationSystem
    {
        public int IrrigationSysID { get; set; }
        public Nullable<int> MunicipalityID { get; set; }
        public Nullable<decimal> AreasIrrigable { get; set; }
        public Nullable<decimal> NatlIrrigationSys { get; set; }
        public Nullable<decimal> NIAAssisted { get; set; }
        public Nullable<decimal> OtherAgency { get; set; }
        public Nullable<decimal> PrivateIrrigation { get; set; }
        public Nullable<decimal> PumpSystem { get; set; }
        public Nullable<decimal> IrrigationDev { get; set; }
        public Nullable<decimal> RemainingAreas { get; set; }
        public string YearTaken { get; set; }
    }
}
