//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LivestockPoultryInventory
    {
        public int LivestockInvID { get; set; }
        public Nullable<int> MunicipalityID { get; set; }
        public Nullable<int> LivestockPoultryID { get; set; }
        public Nullable<int> NumberofLivestock { get; set; }
        public string YearTaken { get; set; }
    }
}
