//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_StrategicPriorityGroup
    {
        public int StrategicPriorityGrpID { get; set; }
        public string StrategicPriorityGrpCode { get; set; }
        public string StrategicPriorityGrpDescription { get; set; }
    }
}
