//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_BDIPperMunicipality
    {
        public int BDIPID { get; set; }
        public Nullable<int> MunicipalityID { get; set; }
        public string BDIPMunicipalityCode { get; set; }
        public string BDIPMunicipality { get; set; }
    }
}
