//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_Holiday
    {
        public int HolidayID { get; set; }
        public string HolidayDescription { get; set; }
        public Nullable<System.DateTime> HolidayDate { get; set; }
        public Nullable<int> DayTypeID { get; set; }
        public Nullable<decimal> NoOfHours { get; set; }
    }
}
