//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_DepartmentUnit
    {
        public int DepartmentUnitID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string DepartmentUnitCode { get; set; }
        public string DepartmentUnitDescription { get; set; }
    }
}
