//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_Regions
    {
        public int regionID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string RegionName { get; set; }
        public string RegionalDesignation { get; set; }
    }
}
