//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_HouseholdHighestEducationAttained
    {
        public int PopEducationAttainedID { get; set; }
        public string HighestEducAttainedDesc { get; set; }
        public Nullable<int> TotalPerEducAttaineed { get; set; }
        public Nullable<int> OverAllTotal { get; set; }
        public Nullable<int> MalePopulation { get; set; }
        public Nullable<int> FemalePopulation { get; set; }
        public string YearTaken { get; set; }
        public Nullable<int> HighestEducAttainedID { get; set; }
    }
}
