//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_PopulationDistributionByYearByMunicipality
    {
        public Nullable<int> MunicipalityID { get; set; }
        public string Municipality { get; set; }
        public Nullable<int> TotalPopulation { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<decimal> PopulationDistribution { get; set; }
        public string YearTaken { get; set; }
        public int PopDistributionID { get; set; }
    }
}
