//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_appUsers
    {
        public Nullable<int> empid { get; set; }
        public string roles { get; set; }
        public string Fullname { get; set; }
        public int appuserid { get; set; }
    }
}
