//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClimateChangeTypology
    {
        public int TypologyID { get; set; }
        public string StrategicPriorityDescription { get; set; }
        public string StrategicPriorityAreaDescription { get; set; }
        public string StrategicPriorityClassification { get; set; }
        public string StrategicPriorityGrpDescription { get; set; }
        public string TypologyCode { get; set; }
        public string TypologyDescription { get; set; }
    }
}
