//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EstablishmentByIndustryByYear
    {
        public int EstablishID { get; set; }
        public string IndustryClassification { get; set; }
        public Nullable<int> NumberofFirms { get; set; }
        public Nullable<decimal> PercentFirms { get; set; }
        public Nullable<decimal> Investment { get; set; }
        public Nullable<decimal> PercentInvest { get; set; }
        public Nullable<int> NumberofEmployee { get; set; }
        public Nullable<decimal> Distribution { get; set; }
        public string YearTaken { get; set; }
    }
}
