//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmploymentRecord
    {
        public Nullable<int> empID { get; set; }
        public string Company { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PositionDescription { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public string SalaryGradeCode { get; set; }
        public string StepIncrement { get; set; }
        public string EmpStatusDescription { get; set; }
        public Nullable<bool> IsGovService { get; set; }
        public int workID { get; set; }
    }
}
