//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProvinceList
    {
        public int provinceID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string RegionalDesignation { get; set; }
        public string ProvinceDistrict { get; set; }
        public string Capital { get; set; }
    }
}
