//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectProfile
    {
        public int ProjectProfileID { get; set; }
        public Nullable<int> FunctionCode { get; set; }
        public string ProgramCode { get; set; }
        public string ReferenceCode { get; set; }
        public string SectorDescription { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectDescription { get; set; }
        public string ImpDeptCode { get; set; }
        public Nullable<System.DateTime> ProjStartDate { get; set; }
        public Nullable<System.DateTime> ProjEndDate { get; set; }
        public string ProjStatusDescription { get; set; }
        public string ProjExpectedOutput { get; set; }
        public string SourceFundDescription { get; set; }
        public string BDIPMunicipalityCode { get; set; }
        public string ProjCategoryCode { get; set; }
        public string ProjReferenceOutput { get; set; }
        public string ProjItemWork { get; set; }
        public string Municipality { get; set; }
        public string Barangay { get; set; }
        public string ProjPurok { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> ProjPS { get; set; }
        public Nullable<decimal> ProjMOOE { get; set; }
        public Nullable<decimal> ProjCapitalOutlay { get; set; }
        public Nullable<decimal> TotalBudget { get; set; }
        public string StrategicPriorityDescription { get; set; }
        public string StrategicPriorityAreaDescription { get; set; }
        public string Mitigation { get; set; }
        public string Adaptation { get; set; }
    }
}
