//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualInvestmentProgram
    {
        public int AIPid { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> AIPLevel2ID { get; set; }
        public Nullable<int> AIPLevel3ID { get; set; }
        public Nullable<int> AIPLevel4ID { get; set; }
        public Nullable<int> AIPLevel5ID { get; set; }
        public Nullable<int> AIPLevel6ID { get; set; }
        public Nullable<int> LGULevelID { get; set; }
        public Nullable<int> OfficeTypeID { get; set; }
        public Nullable<int> ImplementingDeptID { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjActivities { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ProjStatusID { get; set; }
        public Nullable<int> SourceFundID { get; set; }
        public string ExpectedOutput { get; set; }
        public Nullable<int> ProjCatID { get; set; }
        public string ReferenceDoc { get; set; }
        public string ItemWork { get; set; }
        public Nullable<int> MunicipalityID { get; set; }
        public Nullable<int> barangayID { get; set; }
        public string ProjPurok { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> ProjPS { get; set; }
        public Nullable<decimal> ProjMOOE { get; set; }
        public Nullable<decimal> ProjCapitalOutlay { get; set; }
        public Nullable<int> StrategicPriorityID { get; set; }
        public Nullable<int> StrategicPriorityAreaID { get; set; }
        public Nullable<int> MitigationTypologyID { get; set; }
        public Nullable<int> AdaptationTypologyID { get; set; }
        public Nullable<decimal> CCMitigationAmount { get; set; }
        public Nullable<decimal> CCAdaptationAmount { get; set; }
    }
}
