//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeProduction
    {
        public int CoffeeProdID { get; set; }
        public Nullable<int> MunicipalityID { get; set; }
        public Nullable<int> CoffeeID { get; set; }
        public Nullable<int> AreaHectares { get; set; }
        public Nullable<decimal> TotalProd { get; set; }
        public string YearTaken { get; set; }
    }
}
