//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropDown_AttendanceMonth
    {
        public Nullable<int> empAttendanceMainID { get; set; }
        public string AttendanceMonth { get; set; }
        public int AttendanceDetailDTRId { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
