//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropDown_AIPLevel4
    {
        public int AIPLevel4ID { get; set; }
        public string Level4 { get; set; }
        public int AIPLevel3ID { get; set; }
    }
}
