//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_LeaveBalance
    {
        public int LeaveBalanceID { get; set; }
        public int empID { get; set; }
        public int LeaveTypeID { get; set; }
        public Nullable<decimal> LeaveBalance { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<decimal> LastUpdatedBalance { get; set; }
    }
}
