//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAttendanceDetailDTR
    {
        public int AttendanceDetailDTRId { get; set; }
        public Nullable<int> empAttendanceMainID { get; set; }
        public Nullable<System.DateTime> DTRDate { get; set; }
        public Nullable<int> empID { get; set; }
        public string In1 { get; set; }
        public string Out1 { get; set; }
        public string In2 { get; set; }
        public string Out2 { get; set; }
        public string In3 { get; set; }
        public string Out3 { get; set; }
        public string In4 { get; set; }
        public string Out4 { get; set; }
        public string HrsWorked { get; set; }
        public Nullable<decimal> HrsWorkedDec { get; set; }
        public string AbsHrs { get; set; }
        public Nullable<decimal> AbsHrsDec { get; set; }
        public string OTHrs { get; set; }
        public Nullable<decimal> OTHrsDec { get; set; }
        public string LateHrs { get; set; }
        public Nullable<decimal> LateHrsDec { get; set; }
        public string UnderTimeHours { get; set; }
        public Nullable<decimal> UnderTimeHoursDec { get; set; }
        public Nullable<decimal> LeaveHrs { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
    }
}
