//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpEmploymentRecord
    {
        public int empRecID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<decimal> MonthlySalary { get; set; }
        public Nullable<int> SalaryGradeID { get; set; }
        public Nullable<int> SGIncrementID { get; set; }
        public Nullable<int> AppointmentStatusID { get; set; }
        public Nullable<int> FirstApprover { get; set; }
        public Nullable<int> SecondApprover { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
        public Nullable<bool> IsSeparated { get; set; }
    }
}
