//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpLeaveApplication
    {
        public int empLeaveAppID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> empAttendanceMainID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<System.DateTime> DateFiled { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> AppliedHours { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public bool IsWithPay { get; set; }
        public bool IsCancelled { get; set; }
        public string Remarks { get; set; }
        public byte[] StampTime { get; set; }
        public Nullable<int> AttendanceDetailDTRId { get; set; }
    }
}
