//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpMasterProfile
    {
        public int empid { get; set; }
        public string empNo { get; set; }
        public Nullable<int> namePrefixTitleID { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> nameSuffixTitleID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public string street { get; set; }
        public Nullable<int> BarangayID { get; set; }
        public Nullable<int> MunicipalityID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string zipCode { get; set; }
        public string residentialPhoneNo { get; set; }
        public string street2 { get; set; }
        public Nullable<int> BarangayID2 { get; set; }
        public Nullable<int> MunicipalityID2 { get; set; }
        public Nullable<int> ProvinceID2 { get; set; }
        public Nullable<int> CountryID2 { get; set; }
        public string zipCode2 { get; set; }
        public string residentialPhoneNo2 { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string birthPlace { get; set; }
        public Nullable<int> CivilStatusID { get; set; }
        public Nullable<int> CitizenshipID { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<int> BloodTypeID { get; set; }
        public string GSIS { get; set; }
        public string HDMF { get; set; }
        public string PhilHealth { get; set; }
        public string SSS { get; set; }
        public string TIN { get; set; }
        public string LandLineNo { get; set; }
        public string CellphoneNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
        public Nullable<int> FirstApprover { get; set; }
        public Nullable<int> SecondApprover { get; set; }
        public Nullable<bool> IsSeparated { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> DepartmentUnitID { get; set; }
        public Nullable<int> AppointmentStatusID { get; set; }
        public Nullable<int> PositionID { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public Nullable<decimal> CurrentSalary { get; set; }
        public string DisplayPicturePath { get; set; }
        public Nullable<int> RegionID { get; set; }
        public Nullable<int> RegionID2 { get; set; }
        public Nullable<int> YearsInService { get; set; }
        public Nullable<int> MonthsInService { get; set; }
    }
}
