//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpOffset
    {
        public int OffsetAppID { get; set; }
        public Nullable<int> AttendanceDetailDTRId { get; set; }
        public Nullable<int> empAttendanceMainID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<System.DateTime> OTDateApplied { get; set; }
        public Nullable<System.DateTime> DateAcquired { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<decimal> OffsetAppliedHrsDEC { get; set; }
        public string OffsetAppliedHrs { get; set; }
    }
}
