//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpOvertime
    {
        public int empOTID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> AttendanceDetailDTRId { get; set; }
        public string In1 { get; set; }
        public string Out1 { get; set; }
        public string OTReason { get; set; }
        public Nullable<decimal> AppliedOTHoursDEC { get; set; }
        public string AppliedOTHoursCHAR { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public bool IsApproved { get; set; }
        public bool IsDenied { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
    }
}
