//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForestCoverVegetation
    {
        public int VegetationID { get; set; }
        public Nullable<int> LandCoverClassID { get; set; }
        public Nullable<decimal> AreaHectares { get; set; }
        public Nullable<decimal> Distribution { get; set; }
        public string YearTaken { get; set; }
    }
}
