//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherCropsProduction
    {
        public int OtherCropsProdID { get; set; }
        public Nullable<int> HighValueCropID { get; set; }
        public Nullable<int> AreaHectares { get; set; }
        public Nullable<decimal> ProdMetricTons { get; set; }
        public string YearTaken { get; set; }
    }
}
