//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopulationByReligiousAffiliation
    {
        public int PopReligionID { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> NumberofHouseholds { get; set; }
        public string YearTaken { get; set; }
    }
}
