//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopulationMigrationRate
    {
        public int PopMigrationID { get; set; }
        public Nullable<int> MunicipalityID { get; set; }
        public Nullable<int> MigratingIN { get; set; }
        public Nullable<decimal> MigratingINPer { get; set; }
        public Nullable<int> MigratingOUT { get; set; }
        public Nullable<decimal> MigratingOUTPer { get; set; }
        public string YearTaken { get; set; }
    }
}
