//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProfile
    {
        public int ProjectProfileID { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> AccountCodeID { get; set; }
        public Nullable<int> OfficialCodeID { get; set; }
        public string LineNumber { get; set; }
        public Nullable<int> SectorID { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<int> ImpDeptID { get; set; }
        public Nullable<System.DateTime> ProjStartDate { get; set; }
        public Nullable<System.DateTime> ProjEndDate { get; set; }
        public Nullable<int> ProjStatusID { get; set; }
        public string ProjExpectedOutput { get; set; }
        public Nullable<int> SourceFundID { get; set; }
        public Nullable<int> BDIPID { get; set; }
        public Nullable<int> ProjCatID { get; set; }
        public string ProjReferenceOutput { get; set; }
        public string ProjItemWork { get; set; }
        public Nullable<int> MunicipalityID { get; set; }
        public Nullable<int> barangayID { get; set; }
        public string ProjPurok { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> ProjPS { get; set; }
        public Nullable<decimal> ProjMOOE { get; set; }
        public Nullable<decimal> ProjCapitalOutlay { get; set; }
        public Nullable<int> StrategicPriorityID { get; set; }
        public Nullable<int> StrategicPriorityAreaID { get; set; }
        public Nullable<int> MitigationTypologyID { get; set; }
        public Nullable<int> AdaptationTypologyID { get; set; }
    }
}
