//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSignatory
    {
        public int SignatoryID { get; set; }
        public string PlanningOfficer { get; set; }
        public string BudgetOfficer { get; set; }
        public string LocExecOfficer { get; set; }
        public Nullable<System.DateTime> DateEncoded { get; set; }
    }
}
