//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_ImplementingDept
    {
        public int ImplementingDeptID { get; set; }
        public Nullable<int> LGULevelID { get; set; }
        public Nullable<int> OfficeTypeID { get; set; }
        public string ImplementingDeptDesc { get; set; }
        public string ImplementingDeptCode { get; set; }
    }
}
