//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_AIP5thLevel
    {
        public int AIPLevel5ID { get; set; }
        public Nullable<int> AIPLevel4ID { get; set; }
        public string AIPLevel5Description { get; set; }
        public string AIPLevel5Code { get; set; }
    }
}
