//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_SalaryGrade
    {
        public int SalaryGradeID { get; set; }
        public string SalaryGradeCode { get; set; }
        public string SalaryGradeDescription { get; set; }
    }
}
