//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_AIPLevel2
    {
        public int AIPLevel2ID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public string AIPLevel2Code { get; set; }
        public string AIPLevel2Description { get; set; }
    }
}
