//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep_EmpLeaveApplication
    {
        public int empLeaveAppID { get; set; }
        public Nullable<int> empID { get; set; }
        public string Fullname { get; set; }
        public string LeaveTypeDescription { get; set; }
        public Nullable<System.DateTime> DateFiled { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> AppliedHours { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsCancelled { get; set; }
        public string Supervisor { get; set; }
        public Nullable<System.DateTime> DateAction { get; set; }
        public Nullable<int> empAttendanceMainID { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<bool> IsWithPay { get; set; }
    }
}
