//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_AIPLevel4
    {
        public int AIPLevel4ID { get; set; }
        public string AIPCodeLevel1 { get; set; }
        public string AIPCodeLevel2 { get; set; }
        public string AIPCodeLevel3 { get; set; }
        public string AIPLevel4Code { get; set; }
        public string AIPLevel4Description { get; set; }
    }
}
