//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rep_AIPLevel3
    {
        public int AIPLevel3ID { get; set; }
        public string AIPCodeLevel1 { get; set; }
        public string AIPCodeLevel2 { get; set; }
        public string AIPLevel3Code { get; set; }
        public string AIPLevel3Description { get; set; }
    }
}
