//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AccountCodes
    {
        public int AccountCodeID { get; set; }
        public string StrategicPriority { get; set; }
        public string Program { get; set; }
        public Nullable<int> AccountCode { get; set; }
        public string AccountDescription { get; set; }
    }
}
