//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AttendanceDetailDTR
    {
        public int AttendanceDetailDTRId { get; set; }
        public Nullable<int> empAttendanceMainID { get; set; }
        public Nullable<int> empID { get; set; }
        public string NameDay { get; set; }
        public Nullable<int> DayNum { get; set; }
        public string NumDay { get; set; }
        public string HrsWorked { get; set; }
        public Nullable<decimal> HrsWorkedDec { get; set; }
        public string AbsHrs { get; set; }
        public Nullable<decimal> AbsHrsDec { get; set; }
        public string OTHrs { get; set; }
        public Nullable<decimal> OTHrsDec { get; set; }
        public string LateHrs { get; set; }
        public Nullable<decimal> LateHrsDec { get; set; }
        public string UnderTimeHours { get; set; }
        public Nullable<decimal> UnderTimeHoursDec { get; set; }
        public Nullable<decimal> LeaveHrs { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
    }
}
