//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ClassOfWorker
    {
        public int WorkersByClassID { get; set; }
        public string ClassWorkerDesc { get; set; }
        public Nullable<int> NumberofPopulation { get; set; }
        public string genderDescription { get; set; }
        public string AgeGroup { get; set; }
        public string YearTaken { get; set; }
    }
}
