//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmpAppliedOvertime
    {
        public int empOTID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public Nullable<int> AttendanceDetailDTRId { get; set; }
        public Nullable<System.DateTime> DTRDate { get; set; }
        public string LOGIN { get; set; }
        public string LOGOUT { get; set; }
        public Nullable<decimal> AppliedOTHoursDEC { get; set; }
        public string AppliedOTHoursCHAR { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsDenied { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
    }
}
