//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmployeeList
    {
        public int empid { get; set; }
        public string EmployeeName { get; set; }
        public string empNo { get; set; }
        public string PositionDescription { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string EmpStatusDescription { get; set; }
        public string DeptDescription { get; set; }
        public string CivilStatusDescription { get; set; }
    }
}
