//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EducationHistory
    {
        public Nullable<int> empID { get; set; }
        public string EducLevel { get; set; }
        public string SchoolName { get; set; }
        public string Degree { get; set; }
        public string YearGraduated { get; set; }
        public string Earned { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Distinction { get; set; }
        public int empEducID { get; set; }
    }
}
