//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_EmployeePersonalProfile
    {
        public int empid { get; set; }
        public string empNo { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string genderDescription { get; set; }
        public string religionDescription { get; set; }
        public string residentialPhoneNo { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string birthPlace { get; set; }
        public string Nationality { get; set; }
        public string GSIS { get; set; }
        public string HDMF { get; set; }
        public string PhilHealth { get; set; }
        public string SSS { get; set; }
        public string TIN { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public string Barangay { get; set; }
        public string Municipality { get; set; }
        public string ProvinceDistrict { get; set; }
        public string CivilStatusDescription { get; set; }
        public string BloodTypeCode { get; set; }
        public string DepartmentUnitDescription { get; set; }
        public string EmpStatusDescription { get; set; }
        public string PositionDescription { get; set; }
    }
}
