//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StrategicPriorityArea
    {
        public Nullable<int> StrategicPriorityNo { get; set; }
        public Nullable<int> StrategicPriorityAreaNo { get; set; }
        public string StrategicPriorityAreaDescription { get; set; }
        public int StrategicPriorityAreaID { get; set; }
        public string StrategicPriorityDescription { get; set; }
    }
}
