//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalingaCMSFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VolunteerList
    {
        public int empVolID { get; set; }
        public int empID { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationAddress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string HoursVolunteered { get; set; }
        public string InvolvementTypeDescription { get; set; }
        public string OrganizationNature { get; set; }
    }
}
